---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      networkservicemesh.io/app: "icmp-responder"
      networkservicemesh.io/impl: "simple-endpoint"
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "icmp-responder"
        networkservicemesh.io/impl: "simple-endpoint"
    spec:
      serviceAccount: nsm-acc
      containers:
        - name: sidecar-endpoint
          image: networkservicemesh/icmp-dns-sidecar-nse:latest
          command: ["/bin/sidecar-nse", "-dns"]
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "icmp-responder"
            - name: ENDPOINT_LABELS
              value: "app=simple-endpoint"
            - name: TRACER_ENABLED
              value: "false"
            - name: IP_ADDRESS
              value: "10.60.1.0/24"
            - name: DNS_SEARCH_DOMAINS
              value: "icmp.app"
          resources:
            limits:
              networkservicemesh.io/socket: 1
        - name: alpine
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]
        - name: coredns
          image: networkservicemesh/coredns:master
          imagePullPolicy: IfNotPresent
          args: ["-conf", "/etc/coredns/Corefile"]
          volumeMounts:
          - mountPath: /etc/coredns
            name: nsm-coredns-volume
      initContainers:
        - name: nse-dns-init
          image: networkservicemesh/icmp-dns-nse-dns-init:latest
          command: ["/bin/nse-dns-init"]
          imagePullPolicy: IfNotPresent
          env:
            - name: EXTERNAL_DNS_IP
              value: "10.101.33.51"
            - name: DNS_SEARCH_DOMAIN
              value: "icmp.app"
          volumeMounts:
          - mountPath: /etc/coredns
            name: nsm-coredns-volume
      volumes:
      - emptyDir: {}
        name: nsm-coredns-volume
metadata:
  name: simple-endpoint