---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      device: "router3"
  replicas: 1
  template:
    metadata:
      labels:
        app: "topo"
        device: "router3"
    spec:
      serviceAccount: nsc-acc
      containers:
        - name: sidecar-nsc
          image: networkservicemesh/topology-sidecar-nsc:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              networkservicemesh.io/socket: "1"
          env:
            - name: NS_NETWORKSERVICEMESH_IO
              value: "topo/eth34?link=r3-r4&peerif=eth43"
        - name: sidecar-nse
          image: networkservicemesh/topology-sidecar-nse:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENDPOINT_NETWORK_SERVICE
              value: "topo"
            - name: ENDPOINT_LABELS
              value: "device=router3"
            - name: TRACER_ENABLED
              value: "true"
            - name: JAEGER_AGENT_HOST
              value: jaeger.nsm-system
            - name: JAEGER_AGENT_PORT
              value: "6831"              
            - name: IP_ADDRESS
              value: "10.60.3.0/24"
            - name: NSM_NAMESPACE
              value: "nsm-system"
          resources:
            limits:
              networkservicemesh.io/socket: "1"
        - name: router
          image: networkservicemesh/topology-qrtr:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: startup-config
              mountPath: /etc/quagga/zebra.conf
              subPath: zebra.conf
      volumes:
        - name: startup-config
          configMap:
            name: qrtr-3
metadata:
  name: "router3"
  namespace: default
---
apiVersion: v1
metadata:
  name: qrtr-3
  namespace: default
data:
  zebra.conf: |
    !
    hostname qrtr-3
    !
    interface lo
      ip address 192.0.2.3/32
      exit
    !
kind: ConfigMap
