---
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      networkservicemesh.io/app: "smf"
      app: smf
  replicas: 1
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "smf"
        app: smf
    spec:
      hostname: smf
      containers:
        - name: smf
          image: free5gc-compose_free5gc-smf
          imagePullPolicy: Never
          command: ['sh', '-c', "until nslookup nrf.default.svc.cluster.local && nslookup upf-pfcp.5g-network.nsm.local && nslookup n4.5g-network.nsm.local && nslookup upf.5g-network.nsm.local; do sleep 2; done; ./smf -smfcfg ../config/smfcfg.conf -uerouting ../config/uerouting.yaml;"]
          # command: ["./smf", "-smfcfg", "../config/smfcfg.conf", "-uerouting", "../config/uerouting.yaml"]
          # securityContext:
          #   capabilities:
          #     add: ["NET_ADMIN"]
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/smfcfg.conf
              subPath: smfcfg.conf
            - name: uerouting
              mountPath: /free5gc/config/uerouting.yaml
              subPath: uerouting.yaml
            - name: free5gc-config
              mountPath: /free5gc/config/free5GC.conf
              subPath: free5GC.conf
          readinessProbe:
            exec:
              command: ['sh', '-c', 'test `ps cax | grep smf | grep -v grep | wc -l` = "1"'] 
          ports:
            - containerPort: 29502
          env:
            - name: GIN_MODE
              value: release
      initContainers:
        # - name: init-wait-upf
        #   image: busybox:1.28
        #   command: ['sh', '-c', "until nslookup upf.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        # - name: init-wait-nrf
        #   image: busybox:1.28
        #   command: ['sh', '-c', "until nslookup nrf.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        # - name: init-sleep
        #   image: busybox:1.28
        #   command: ['sh', '-c', "sleep 10;"]
      volumes:
        - name: config
          configMap:
            name: smf-config
        - name: uerouting
          configMap:
            name: uerouting-config
        - name: free5gc-config
          configMap:
            name: free5gc-config
metadata:
  name: "smf"
  namespace: default
  annotations:
    ns.networkservicemesh.io: 5g-network?app=n4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: default
data:
  smfcfg.conf: |
    info:
      version: 1.0.0
      description: SMF initial local configuration

    configuration:
      smfName: SMF
      sbi:
        scheme: http
        registerIPv4: smf.default.svc.cluster.local # IP used to register to NRF
        bindingIPv4: smf  # IP used to bind the service
        port: 29502
        tls:
          key: gofree5gc/support/TLS/smf.key
          pem: gofree5gc/support/TLS/smf.pem
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
        - nsmf-oam
      snssai_info:
        - sNssai:
            sst: 1
            sd: 010203
          dnnSmfInfoList:
            - dnn: internet
        - sNssai:
            sst: 1
            sd: 112233
          dnnSmfInfoList:
            - dnn: internet
      pfcp:
        addr: n4.5g-network.nsm.local
      userplane_information:
        up_nodes:
          gNB1:
            type: AN
            an_ip: 192.188.2.3
          UPF:
            type: UPF
            node_id: upf-pfcp.5g-network.nsm.local
        links:
          - A: gNB1
            B: UPF
      dnn:
        internet:
          dns:
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        internet2:
          dns:
            ipv4: 8.8.4.4
            ipv6: 2001:4860:4860::8844
      ue_subnet: 60.60.0.0/16
      nrfUri: http://nrf.default.svc.cluster.local:29510
      ulcl: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uerouting-config
  namespace: default
data:
  uerouting.yaml: |
    info:
      version: 1.0.0
      description: Routing information for UE
---
apiVersion: v1
kind: Service
metadata:
  name: smf
spec:
  selector:
    app: smf
  clusterIP: None